#! /bin/sh

set -x

rootdir=`pwd`
echo ${rootdir}

find . -name autom4te\.cache -exec \rm -rf {} \; -print 

for dir in basic_toolkit bmlfactory mxyzptlk physics_toolkit integrator
do
  cd   $dir
  ${rootdir}/updateheaders
  cd ./src
  ${rootdir}/updatesource
  cd ../..
done

cd   beamline
${rootdir}/updateheaders
cd ./src
${rootdir}/updatesource
cd physics/6d
${rootdir}/updatesource
cd ../mad
${rootdir}/updatesource
cd ../../../..

aclocal -I config
#autoheader
automake --add-missing --foreign --copy
autoconf
#libtoolize --force --copy


for dir in basic_toolkit beamline bmlfactory mxyzptlk physics_toolkit integrator
do
  cd $dir
  aclocal -I config
  autoheader
  automake --add-missing --foreign --copy
  autoconf
  libtoolize --force --copy
  cd ..
done
