#! /bin/sh

set -x

aclocal -I config
#autoheader
automake --add-missing --foreign --copy
autoconf
#libtoolize --force --copy

for dir in basic_toolkit beamline bmlfactory mxyzptlk physics_toolkit integrator
do
  cd $dir
  aclocal -I config
  autoheader
  automake --add-missing --foreign --copy
  autoconf
  libtoolize --force --copy
  cd ..
done
