#!/bin/sh

####################################################################
## bootstrap: a script to generate a build environment 
## using the GNU autotools
## 
## Author: Jean-Francois Ostiguy
##         Fermilab
##         ostiguy@fnal.gov
##
########################################################################

set -x

rootdir=`pwd`

## remove remnants of autogenerated files. These files should **never** be put in the
## repository !

find . -name autom4te\.cache -exec  \rm -rf {}  \; -print 
find . -name aclocal\.m4      -exec \rm     {}  \; -print 
find . -name ltmain\.sh       -exec \rm     {}  \; -print 
find . -name config\.guess    -exec \rm     {}  \; -print 
find . -name config\.sub      -exec \rm     {}  \; -print 

## update the list of source files and header files. 

for dir in basic_toolkit bmlfactory mxyzptlk physics_toolkit integrator gms beamline
do
  echo 'Entering directory: '$dir
  cd   $dir
  if [ ! -L $dir ]
  then ln -s include $dir
  fi
  ${rootdir}/updateheaders.sh
  cd ./src
  ${rootdir}/updatesource.sh
  cd ../..
  echo 'Exiting directory: '$dir
done

for dir in python-bindings
do
  cd   $dir
  echo 'Entering directory'$dir
  ${rootdir}/updateheaders.sh
  echo 'Exiting directory: '$dir
  cd ..
done


## use autotools to generate the build environment. 
## NOTE:  command invocation order matters !

for dir in . basic_toolkit beamline bmlfactory parsers parsers/xsif mxyzptlk physics_toolkit integrator gms python-bindings 
do
  echo 'Entering directory: '$dir
  top=`pwd`
  cd $dir  
  libtoolize --force --copy
  aclocal -I config
  if [ -d src ]; then 
      autoheader
  fi
  automake --add-missing --foreign --copy
  autoconf
  echo 'Exiting directory: '$dir
  cd $top
done

##----------------------------------------
## create links for include subdirectories
##----------------------------------------


echo "Creating header file links ..."

if [ ! -d ./include ]
then mkdir include
fi

cd ./include

for dir in basic_toolkit beamline bmlfactory mxyzptlk physics_toolkit integrator gms python-bindings
do

if [ ! -L $dir ]; then
 ln -s ../$dir/include $dir
fi

done

if [ ! -d ./parsers ]; then
 mkdir parsers
fi

if [ ! -L parsers/xsif ]; then
 ln -s ../../parsers/xsif/include parsers/xsif
fi

cd ..
