#! /bin/tcsh

more source_files | tr " " "\n" > test.source_files.old
setenv current_dir $cwd
while !( -d $cwd/include )
cd ..
end
setenv libname `basename $cwd`
cd $current_dir
unsetenv current_dir
# note yacc sources must come *before* lex sources !
echo lib$libname"_la_SOURCES" = *.{cc,c,y,l,C} > source_files
unsetenv libname
more source_files | tr " " "\n" > test.source_files.new
diff test.source_files.old test.source_files.new | sed "s/</Removed/g" | sed "s/>/Added/g"
rm test.source_files.old
rm test.source_files.new
