#!/bin/sh

cat source_files | tr " " "\n" > test.source_files.old
current_dir=`pwd`
while [ ! -d ./include ]
do
    cd ..
done
libname=`basename \`pwd\``
cd $current_dir
# note yacc sources must come *before* lex sources !
sources="`ls *.cpp` `ls *.cxx` `ls *.cc` `ls  *.c` `ls *.y` `ls *.l` `ls *.C`"
echo lib$libname"_la_SOURCES" = $sources > source_files
cat source_files | tr " " "\n" > test.source_files.new
diff test.source_files.old test.source_files.new | sed "s/</Removed/g" | sed "s/>/Added/g"
rm test.source_files.old
rm test.source_files.new
