#######################################################
## 
## File: Makefile for directory basic_toolkit/tests
## 
## This Makefile requires that three environment variables 
## be predefined: INSTALLDIR, BOOST_INC and BOOST_LIB
## 
## It is purposely written using the minimal number
## of libraries and include directories. In this
## way, CHEF's hierarchy is also tested.
## 
## Leo Michelotti
## 
## Original: Thursday, November 15, 2007
## Revised : Tuesday,  December 16, 2014
## 
#######################################################

.SUFFIXES: .o .cc 

C++        = g++

INCS       = -I$(BOOST_INC) \
             -I$(INSTALLDIR)/include

LIBS       = -L$(INSTALLDIR)/lib -lbasic_toolkit \
             -Wl,-rpath,$(INSTALLDIR)/lib 

## OBSOLETE: SYSLIBS    = -L/usr/local/lib -Wl,-rpath,/usr/local/lib -lboost_system \
## OBSOLETE:              -L/usr/lib64 -Wl,-rpath,/usr/lib64 -lglib-2.0 -lm -lnsl

SYSLIBS    = -L$(BOOST_LIB) -Wl,-rpath,$(BOOST_LIB) -lboost_system

.cc.o:
	$(C++) $(C++FLAGS) $(INCS) -c $*.cc
.o :
	$(C++) $(C++FLAGS) -o $@ $< $(LIBS) $(SYSLIBS)
.cc :
	$(C++) $(C++FLAGS) $(INCS) -o $@ $< $(LIBS) $(SYSLIBS)
