#######################################################
## 
## File: Makefile for directory beamline/tests
## 
## This Makefile requires that three environment variables 
## be predefined: INSTALLDIR, BOOST_INC and BOOST_LIB
## 
## Leo Michelotti
## 
## Original: March 25, 2008
## Revised : January 5, 2015
## 
#######################################################


.SUFFIXES: .o .cpp .cc 

CPP        = g++

INCS       = -I$(BOOST_INC) \
             -I$(INSTALLDIR)/include

LIBS       = -L$(INSTALLDIR)/lib \
             -lbeamline \
             -lmxyzptlk \
             -lbasic_toolkit \
             -Wl,-rpath,$(INSTALLDIR)/lib 

SYSLIBS    = -L$(BOOST_LIB) -Wl,-rpath,$(BOOST_LIB) -lboost_system

.cc.o:
	$(CPP) $(CPPFLAGS) $(INCS) -c $*.cc
.o :
	$(CPP) $(CPPFLAGS) -o $@ $< $(LIBS) $(SYSLIBS)
.cc :
	$(CPP) $(CPPFLAGS) $(INCS) -o $@ $< $(LIBS) $(SYSLIBS)
