#######################################################
## 
## File: Makefile for directory mxyzptlk/tests
## 
## This Makefile requires that three environment variables 
## be predefined: INSTALLDIR, BOOST_INC and BOOST_LIB
## 
## It is purposely written using the minimal number
## of libraries and include directories.  In this
## way, CHEF's hierarchy is also tested.
## 
## Leo Michelotti
## 
## Original: Wednesday, February 13, 2008
## Revised : Wednesday, December 17, 2014
## 
#######################################################


.SUFFIXES: .o .cc 

C++        = g++

INCS       = -I$(BOOST_INC) \
             -I$(INSTALLDIR)/include

LIBS       = -L$(INSTALLDIR)/lib -lmxyzptlk -lbasic_toolkit \
             -Wl,-rpath,$(INSTALLDIR)/lib 

SYSLIBS    = -L$(BOOST_LIB) -Wl,-rpath,$(BOOST_LIB) -lboost_system

.cc.o:
	$(C++) $(C++FLAGS) $(INCS) -c $*.cc
.o :
	$(C++) $(C++FLAGS) -o $@ $< $(LIBS) $(SYSLIBS)
.cc :
	$(C++) $(C++FLAGS) $(INCS) -o $@ $< $(LIBS) $(SYSLIBS)
